services:
  flyway:
    build: .
    image: ozanemrahyakupoglu/may-flyway:${VERSION:-1.0.0}
    container_name: may-flyway
    environment:
      DB_HOST: 46.225.97.71
      DB_PORT: 7000
      DB_USER: postgres
      DB_PASSWORD: 123456789
