flyway.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/postgres?currentSchema=MAY
flyway.user=${DB_USER}
flyway.password=${DB_PASSWORD}
flyway.schemas=MAY
flyway.locations=filesystem:/flyway/sql
flyway.baselineOnMigrate=true
flyway.validateOnMigrate=false
flyway.outOfOrder=false
