-- =============================================================
-- May Database - Initial Schema
-- =============================================================

-- ---------------------------------------------------------------
-- SCHEMA
-- ---------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS MAY;

-- =============================================================
-- 1. USERS
-- =============================================================
CREATE SEQUENCE MAY.SEQ_USERS START WITH 1 INCREMENT BY 1;

CREATE TABLE MAY.USERS (
    ID                  BIGINT          NOT NULL DEFAULT nextval('MAY.SEQ_USERS'),
    USERNAME            VARCHAR(100)    NOT NULL,
    EMAIL               VARCHAR(150)    NOT NULL,
    PASSWORD_HASH       VARCHAR(255)    NOT NULL,
    FIRST_NAME          VARCHAR(100)    NOT NULL,
    LAST_NAME           VARCHAR(100)    NOT NULL,
    PHONE               VARCHAR(20),
    STATUS              VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    LAST_LOGIN_DATE     TIMESTAMP,
    ERROR_LOGIN_COUNT   INTEGER         NOT NULL DEFAULT 0,
    CREATED_BY          VARCHAR(100)    NOT NULL,
    CREATED_DATE        TIMESTAMP       NOT NULL,
    CREATED_IP          VARCHAR(45)     NOT NULL,
    UPDATED_BY          VARCHAR(100),
    UPDATED_DATE        TIMESTAMP,
    UPDATED_IP          VARCHAR(45),
    CONSTRAINT PK_USERS          PRIMARY KEY (ID),
    CONSTRAINT UK_USERS_USERNAME UNIQUE (USERNAME),
    CONSTRAINT UK_USERS_EMAIL    UNIQUE (EMAIL),
    CONSTRAINT CK_USERS_STATUS   CHECK (STATUS IN ('ACTIVE', 'INACTIVE', 'BLOCKED'))
);

CREATE INDEX IDX_USERS_USERNAME ON MAY.USERS (USERNAME);
CREATE INDEX IDX_USERS_EMAIL    ON MAY.USERS (EMAIL);
CREATE INDEX IDX_USERS_STATUS   ON MAY.USERS (STATUS);

CREATE SEQUENCE MAY.SEQ_USERS_HIS START WITH 1 INCREMENT BY 1;

CREATE TABLE MAY.USERS_HIS (
    ID                  BIGINT          NOT NULL DEFAULT nextval('MAY.SEQ_USERS_HIS'),
    ORIGINAL_ID         BIGINT          NOT NULL,
    USERNAME            VARCHAR(100)    NOT NULL,
    EMAIL               VARCHAR(150)    NOT NULL,
    PASSWORD_HASH       VARCHAR(255)    NOT NULL,
    FIRST_NAME          VARCHAR(100)    NOT NULL,
    LAST_NAME           VARCHAR(100)    NOT NULL,
    PHONE               VARCHAR(20),
    STATUS              VARCHAR(20)     NOT NULL,
    LAST_LOGIN_DATE     TIMESTAMP,
    ERROR_LOGIN_COUNT   INTEGER         NOT NULL,
    CREATED_BY          VARCHAR(100)    NOT NULL,
    CREATED_DATE        TIMESTAMP       NOT NULL,
    CREATED_IP          VARCHAR(45)     NOT NULL,
    UPDATED_BY          VARCHAR(100),
    UPDATED_DATE        TIMESTAMP,
    UPDATED_IP          VARCHAR(45),
    DML_OPERATION       VARCHAR(10),
    DML_BY              VARCHAR(100),
    DML_DATE            TIMESTAMP,
    DML_IP              VARCHAR(45),
    CONSTRAINT PK_USERS_HIS PRIMARY KEY (ID)
);

CREATE INDEX IDX_USERS_HIS_ORIGINAL_ID ON MAY.USERS_HIS (ORIGINAL_ID);

CREATE OR REPLACE FUNCTION MAY.FN_USERS_HIS()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO MAY.USERS_HIS (
            ID, ORIGINAL_ID, USERNAME, EMAIL, PASSWORD_HASH, FIRST_NAME, LAST_NAME,
            PHONE, STATUS, LAST_LOGIN_DATE, ERROR_LOGIN_COUNT,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('MAY.SEQ_USERS_HIS'), NEW.ID, NEW.USERNAME, NEW.EMAIL, NEW.PASSWORD_HASH, NEW.FIRST_NAME, NEW.LAST_NAME,
            NEW.PHONE, NEW.STATUS, NEW.LAST_LOGIN_DATE, NEW.ERROR_LOGIN_COUNT,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'INSERT', NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO MAY.USERS_HIS (
            ID, ORIGINAL_ID, USERNAME, EMAIL, PASSWORD_HASH, FIRST_NAME, LAST_NAME,
            PHONE, STATUS, LAST_LOGIN_DATE, ERROR_LOGIN_COUNT,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('MAY.SEQ_USERS_HIS'), NEW.ID, NEW.USERNAME, NEW.EMAIL, NEW.PASSWORD_HASH, NEW.FIRST_NAME, NEW.LAST_NAME,
            NEW.PHONE, NEW.STATUS, NEW.LAST_LOGIN_DATE, NEW.ERROR_LOGIN_COUNT,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'UPDATE', NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO MAY.USERS_HIS (
            ID, ORIGINAL_ID, USERNAME, EMAIL, PASSWORD_HASH, FIRST_NAME, LAST_NAME,
            PHONE, STATUS, LAST_LOGIN_DATE, ERROR_LOGIN_COUNT,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('MAY.SEQ_USERS_HIS'), OLD.ID, OLD.USERNAME, OLD.EMAIL, OLD.PASSWORD_HASH, OLD.FIRST_NAME, OLD.LAST_NAME,
            OLD.PHONE, OLD.STATUS, OLD.LAST_LOGIN_DATE, OLD.ERROR_LOGIN_COUNT,
            OLD.CREATED_BY, OLD.CREATED_DATE, OLD.CREATED_IP, OLD.UPDATED_BY, OLD.UPDATED_DATE, OLD.UPDATED_IP,
            'DELETE', COALESCE(OLD.UPDATED_BY, OLD.CREATED_BY), COALESCE(OLD.UPDATED_DATE, OLD.CREATED_DATE), COALESCE(OLD.UPDATED_IP, OLD.CREATED_IP)
        );
        RETURN OLD;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRG_USERS_HIS
    AFTER INSERT OR UPDATE OR DELETE ON MAY.USERS
    FOR EACH ROW EXECUTE FUNCTION MAY.FN_USERS_HIS();


-- =============================================================
-- 2. ROLE
-- =============================================================
CREATE SEQUENCE MAY.SEQ_ROLE START WITH 1 INCREMENT BY 1;

CREATE TABLE MAY.ROLE (
    ID              BIGINT          NOT NULL DEFAULT nextval('MAY.SEQ_ROLE'),
    NAME            VARCHAR(100)    NOT NULL,
    DESCRIPTION     VARCHAR(500),
    STATUS          VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    CREATED_BY      VARCHAR(100)    NOT NULL,
    CREATED_DATE    TIMESTAMP       NOT NULL,
    CREATED_IP      VARCHAR(45)     NOT NULL,
    UPDATED_BY      VARCHAR(100),
    UPDATED_DATE    TIMESTAMP,
    UPDATED_IP      VARCHAR(45),
    CONSTRAINT PK_ROLE        PRIMARY KEY (ID),
    CONSTRAINT UK_ROLE_NAME   UNIQUE (NAME),
    CONSTRAINT CK_ROLE_STATUS CHECK (STATUS IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX IDX_ROLE_NAME   ON MAY.ROLE (NAME);
CREATE INDEX IDX_ROLE_STATUS ON MAY.ROLE (STATUS);

CREATE SEQUENCE MAY.SEQ_ROLE_HIS START WITH 1 INCREMENT BY 1;

CREATE TABLE MAY.ROLE_HIS (
    ID              BIGINT          NOT NULL DEFAULT nextval('MAY.SEQ_ROLE_HIS'),
    ORIGINAL_ID     BIGINT          NOT NULL,
    NAME            VARCHAR(100)    NOT NULL,
    DESCRIPTION     VARCHAR(500),
    STATUS          VARCHAR(20)     NOT NULL,
    CREATED_BY      VARCHAR(100)    NOT NULL,
    CREATED_DATE    TIMESTAMP       NOT NULL,
    CREATED_IP      VARCHAR(45)     NOT NULL,
    UPDATED_BY      VARCHAR(100),
    UPDATED_DATE    TIMESTAMP,
    UPDATED_IP      VARCHAR(45),
    DML_OPERATION   VARCHAR(10),
    DML_BY          VARCHAR(100),
    DML_DATE        TIMESTAMP,
    DML_IP          VARCHAR(45),
    CONSTRAINT PK_ROLE_HIS PRIMARY KEY (ID)
);

CREATE INDEX IDX_ROLE_HIS_ORIGINAL_ID ON MAY.ROLE_HIS (ORIGINAL_ID);

CREATE OR REPLACE FUNCTION MAY.FN_ROLE_HIS()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO MAY.ROLE_HIS (
            ID, ORIGINAL_ID, NAME, DESCRIPTION, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('MAY.SEQ_ROLE_HIS'), NEW.ID, NEW.NAME, NEW.DESCRIPTION, NEW.STATUS,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'INSERT', NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO MAY.ROLE_HIS (
            ID, ORIGINAL_ID, NAME, DESCRIPTION, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('MAY.SEQ_ROLE_HIS'), NEW.ID, NEW.NAME, NEW.DESCRIPTION, NEW.STATUS,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'UPDATE', NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO MAY.ROLE_HIS (
            ID, ORIGINAL_ID, NAME, DESCRIPTION, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('MAY.SEQ_ROLE_HIS'), OLD.ID, OLD.NAME, OLD.DESCRIPTION, OLD.STATUS,
            OLD.CREATED_BY, OLD.CREATED_DATE, OLD.CREATED_IP, OLD.UPDATED_BY, OLD.UPDATED_DATE, OLD.UPDATED_IP,
            'DELETE', COALESCE(OLD.UPDATED_BY, OLD.CREATED_BY), COALESCE(OLD.UPDATED_DATE, OLD.CREATED_DATE), COALESCE(OLD.UPDATED_IP, OLD.CREATED_IP)
        );
        RETURN OLD;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRG_ROLE_HIS
    AFTER INSERT OR UPDATE OR DELETE ON MAY.ROLE
    FOR EACH ROW EXECUTE FUNCTION MAY.FN_ROLE_HIS();


-- =============================================================
-- 3. PERMISSION
-- =============================================================
CREATE SEQUENCE MAY.SEQ_PERMISSION START WITH 1 INCREMENT BY 1;

CREATE TABLE MAY.PERMISSION (
    ID              BIGINT          NOT NULL DEFAULT nextval('MAY.SEQ_PERMISSION'),
    NAME            VARCHAR(100)    NOT NULL,
    DESCRIPTION     VARCHAR(500),
    MODULE          VARCHAR(100)    NOT NULL,
    ACTION          VARCHAR(50)     NOT NULL,
    STATUS          VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    CREATED_BY      VARCHAR(100)    NOT NULL,
    CREATED_DATE    TIMESTAMP       NOT NULL,
    CREATED_IP      VARCHAR(45)     NOT NULL,
    UPDATED_BY      VARCHAR(100),
    UPDATED_DATE    TIMESTAMP,
    UPDATED_IP      VARCHAR(45),
    CONSTRAINT PK_PERMISSION                PRIMARY KEY (ID),
    CONSTRAINT UK_PERMISSION_NAME           UNIQUE (NAME),
    CONSTRAINT UK_PERMISSION_MODULE_ACTION  UNIQUE (MODULE, ACTION),
    CONSTRAINT CK_PERMISSION_STATUS         CHECK (STATUS IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT CK_PERMISSION_ACTION         CHECK (ACTION IN ('CREATE', 'READ', 'UPDATE', 'DELETE', 'LIST', 'EXPORT', 'IMPORT'))
);

CREATE INDEX IDX_PERMISSION_NAME   ON MAY.PERMISSION (NAME);
CREATE INDEX IDX_PERMISSION_MODULE ON MAY.PERMISSION (MODULE);
CREATE INDEX IDX_PERMISSION_ACTION ON MAY.PERMISSION (ACTION);
CREATE INDEX IDX_PERMISSION_STATUS ON MAY.PERMISSION (STATUS);

CREATE SEQUENCE MAY.SEQ_PERMISSION_HIS START WITH 1 INCREMENT BY 1;

CREATE TABLE MAY.PERMISSION_HIS (
    ID              BIGINT          NOT NULL DEFAULT nextval('MAY.SEQ_PERMISSION_HIS'),
    ORIGINAL_ID     BIGINT          NOT NULL,
    NAME            VARCHAR(100)    NOT NULL,
    DESCRIPTION     VARCHAR(500),
    MODULE          VARCHAR(100)    NOT NULL,
    ACTION          VARCHAR(50)     NOT NULL,
    STATUS          VARCHAR(20)     NOT NULL,
    CREATED_BY      VARCHAR(100)    NOT NULL,
    CREATED_DATE    TIMESTAMP       NOT NULL,
    CREATED_IP      VARCHAR(45)     NOT NULL,
    UPDATED_BY      VARCHAR(100),
    UPDATED_DATE    TIMESTAMP,
    UPDATED_IP      VARCHAR(45),
    DML_OPERATION   VARCHAR(10),
    DML_BY          VARCHAR(100),
    DML_DATE        TIMESTAMP,
    DML_IP          VARCHAR(45),
    CONSTRAINT PK_PERMISSION_HIS PRIMARY KEY (ID)
);

CREATE INDEX IDX_PERMISSION_HIS_ORIGINAL_ID ON MAY.PERMISSION_HIS (ORIGINAL_ID);

CREATE OR REPLACE FUNCTION MAY.FN_PERMISSION_HIS()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO MAY.PERMISSION_HIS (
            ID, ORIGINAL_ID, NAME, DESCRIPTION, MODULE, ACTION, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('MAY.SEQ_PERMISSION_HIS'), NEW.ID, NEW.NAME, NEW.DESCRIPTION, NEW.MODULE, NEW.ACTION, NEW.STATUS,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'INSERT', NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO MAY.PERMISSION_HIS (
            ID, ORIGINAL_ID, NAME, DESCRIPTION, MODULE, ACTION, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('MAY.SEQ_PERMISSION_HIS'), NEW.ID, NEW.NAME, NEW.DESCRIPTION, NEW.MODULE, NEW.ACTION, NEW.STATUS,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'UPDATE', NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO MAY.PERMISSION_HIS (
            ID, ORIGINAL_ID, NAME, DESCRIPTION, MODULE, ACTION, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('MAY.SEQ_PERMISSION_HIS'), OLD.ID, OLD.NAME, OLD.DESCRIPTION, OLD.MODULE, OLD.ACTION, OLD.STATUS,
            OLD.CREATED_BY, OLD.CREATED_DATE, OLD.CREATED_IP, OLD.UPDATED_BY, OLD.UPDATED_DATE, OLD.UPDATED_IP,
            'DELETE', COALESCE(OLD.UPDATED_BY, OLD.CREATED_BY), COALESCE(OLD.UPDATED_DATE, OLD.CREATED_DATE), COALESCE(OLD.UPDATED_IP, OLD.CREATED_IP)
        );
        RETURN OLD;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRG_PERMISSION_HIS
    AFTER INSERT OR UPDATE OR DELETE ON MAY.PERMISSION
    FOR EACH ROW EXECUTE FUNCTION MAY.FN_PERMISSION_HIS();


-- =============================================================
-- 4. USERS_ROLE
-- =============================================================
CREATE SEQUENCE MAY.SEQ_USERS_ROLE START WITH 1 INCREMENT BY 1;

CREATE TABLE MAY.USERS_ROLE (
    ID              BIGINT          NOT NULL DEFAULT nextval('MAY.SEQ_USERS_ROLE'),
    USERS_ID        BIGINT          NOT NULL,
    ROLE_ID         BIGINT          NOT NULL,
    ASSIGNED_BY     VARCHAR(100)    NOT NULL,
    ASSIGNED_DATE   TIMESTAMP       NOT NULL,
    CREATED_BY      VARCHAR(100)    NOT NULL,
    CREATED_DATE    TIMESTAMP       NOT NULL,
    CREATED_IP      VARCHAR(45)     NOT NULL,
    UPDATED_BY      VARCHAR(100),
    UPDATED_DATE    TIMESTAMP,
    UPDATED_IP      VARCHAR(45),
    CONSTRAINT PK_USERS_ROLE          PRIMARY KEY (ID),
    CONSTRAINT FK_USERS_ROLE_USERS    FOREIGN KEY (USERS_ID) REFERENCES MAY.USERS(ID),
    CONSTRAINT FK_USERS_ROLE_ROLE     FOREIGN KEY (ROLE_ID)  REFERENCES MAY.ROLE(ID),
    CONSTRAINT UK_USERS_ROLE          UNIQUE (USERS_ID, ROLE_ID)
);

CREATE INDEX IDX_USERS_ROLE_USERS_ID ON MAY.USERS_ROLE (USERS_ID);
CREATE INDEX IDX_USERS_ROLE_ROLE_ID  ON MAY.USERS_ROLE (ROLE_ID);

CREATE SEQUENCE MAY.SEQ_USERS_ROLE_HIS START WITH 1 INCREMENT BY 1;

CREATE TABLE MAY.USERS_ROLE_HIS (
    ID              BIGINT          NOT NULL DEFAULT nextval('MAY.SEQ_USERS_ROLE_HIS'),
    ORIGINAL_ID     BIGINT          NOT NULL,
    USERS_ID        BIGINT          NOT NULL,
    ROLE_ID         BIGINT          NOT NULL,
    ASSIGNED_BY     VARCHAR(100)    NOT NULL,
    ASSIGNED_DATE   TIMESTAMP       NOT NULL,
    CREATED_BY      VARCHAR(100)    NOT NULL,
    CREATED_DATE    TIMESTAMP       NOT NULL,
    CREATED_IP      VARCHAR(45)     NOT NULL,
    UPDATED_BY      VARCHAR(100),
    UPDATED_DATE    TIMESTAMP,
    UPDATED_IP      VARCHAR(45),
    DML_OPERATION   VARCHAR(10),
    DML_BY          VARCHAR(100),
    DML_DATE        TIMESTAMP,
    DML_IP          VARCHAR(45),
    CONSTRAINT PK_USERS_ROLE_HIS PRIMARY KEY (ID)
);

CREATE INDEX IDX_USERS_ROLE_HIS_ORIGINAL_ID ON MAY.USERS_ROLE_HIS (ORIGINAL_ID);

CREATE OR REPLACE FUNCTION MAY.FN_USERS_ROLE_HIS()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO MAY.USERS_ROLE_HIS (
            ID, ORIGINAL_ID, USERS_ID, ROLE_ID, ASSIGNED_BY, ASSIGNED_DATE,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('MAY.SEQ_USERS_ROLE_HIS'), NEW.ID, NEW.USERS_ID, NEW.ROLE_ID, NEW.ASSIGNED_BY, NEW.ASSIGNED_DATE,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'INSERT', NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO MAY.USERS_ROLE_HIS (
            ID, ORIGINAL_ID, USERS_ID, ROLE_ID, ASSIGNED_BY, ASSIGNED_DATE,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('MAY.SEQ_USERS_ROLE_HIS'), NEW.ID, NEW.USERS_ID, NEW.ROLE_ID, NEW.ASSIGNED_BY, NEW.ASSIGNED_DATE,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'UPDATE', NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO MAY.USERS_ROLE_HIS (
            ID, ORIGINAL_ID, USERS_ID, ROLE_ID, ASSIGNED_BY, ASSIGNED_DATE,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('MAY.SEQ_USERS_ROLE_HIS'), OLD.ID, OLD.USERS_ID, OLD.ROLE_ID, OLD.ASSIGNED_BY, OLD.ASSIGNED_DATE,
            OLD.CREATED_BY, OLD.CREATED_DATE, OLD.CREATED_IP, OLD.UPDATED_BY, OLD.UPDATED_DATE, OLD.UPDATED_IP,
            'DELETE', COALESCE(OLD.UPDATED_BY, OLD.CREATED_BY), COALESCE(OLD.UPDATED_DATE, OLD.CREATED_DATE), COALESCE(OLD.UPDATED_IP, OLD.CREATED_IP)
        );
        RETURN OLD;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRG_USERS_ROLE_HIS
    AFTER INSERT OR UPDATE OR DELETE ON MAY.USERS_ROLE
    FOR EACH ROW EXECUTE FUNCTION MAY.FN_USERS_ROLE_HIS();


-- =============================================================
-- 5. ROLE_PERMISSION
-- =============================================================
CREATE SEQUENCE MAY.SEQ_ROLE_PERMISSION START WITH 1 INCREMENT BY 1;

CREATE TABLE MAY.ROLE_PERMISSION (
    ID              BIGINT          NOT NULL DEFAULT nextval('MAY.SEQ_ROLE_PERMISSION'),
    ROLE_ID         BIGINT          NOT NULL,
    PERMISSION_ID   BIGINT          NOT NULL,
    CREATED_BY      VARCHAR(100)    NOT NULL,
    CREATED_DATE    TIMESTAMP       NOT NULL,
    CREATED_IP      VARCHAR(45)     NOT NULL,
    UPDATED_BY      VARCHAR(100),
    UPDATED_DATE    TIMESTAMP,
    UPDATED_IP      VARCHAR(45),
    CONSTRAINT PK_ROLE_PERMISSION               PRIMARY KEY (ID),
    CONSTRAINT FK_ROLE_PERMISSION_ROLE          FOREIGN KEY (ROLE_ID)       REFERENCES MAY.ROLE(ID),
    CONSTRAINT FK_ROLE_PERMISSION_PERMISSION    FOREIGN KEY (PERMISSION_ID) REFERENCES MAY.PERMISSION(ID),
    CONSTRAINT UK_ROLE_PERMISSION               UNIQUE (ROLE_ID, PERMISSION_ID)
);

CREATE INDEX IDX_ROLE_PERMISSION_ROLE_ID       ON MAY.ROLE_PERMISSION (ROLE_ID);
CREATE INDEX IDX_ROLE_PERMISSION_PERMISSION_ID ON MAY.ROLE_PERMISSION (PERMISSION_ID);

CREATE SEQUENCE MAY.SEQ_ROLE_PERMISSION_HIS START WITH 1 INCREMENT BY 1;

CREATE TABLE MAY.ROLE_PERMISSION_HIS (
    ID              BIGINT          NOT NULL DEFAULT nextval('MAY.SEQ_ROLE_PERMISSION_HIS'),
    ORIGINAL_ID     BIGINT          NOT NULL,
    ROLE_ID         BIGINT          NOT NULL,
    PERMISSION_ID   BIGINT          NOT NULL,
    CREATED_BY      VARCHAR(100)    NOT NULL,
    CREATED_DATE    TIMESTAMP       NOT NULL,
    CREATED_IP      VARCHAR(45)     NOT NULL,
    UPDATED_BY      VARCHAR(100),
    UPDATED_DATE    TIMESTAMP,
    UPDATED_IP      VARCHAR(45),
    DML_OPERATION   VARCHAR(10),
    DML_BY          VARCHAR(100),
    DML_DATE        TIMESTAMP,
    DML_IP          VARCHAR(45),
    CONSTRAINT PK_ROLE_PERMISSION_HIS PRIMARY KEY (ID)
);

CREATE INDEX IDX_ROLE_PERMISSION_HIS_ORIGINAL_ID ON MAY.ROLE_PERMISSION_HIS (ORIGINAL_ID);

CREATE OR REPLACE FUNCTION MAY.FN_ROLE_PERMISSION_HIS()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO MAY.ROLE_PERMISSION_HIS (
            ID, ORIGINAL_ID, ROLE_ID, PERMISSION_ID,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('MAY.SEQ_ROLE_PERMISSION_HIS'), NEW.ID, NEW.ROLE_ID, NEW.PERMISSION_ID,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'INSERT', NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO MAY.ROLE_PERMISSION_HIS (
            ID, ORIGINAL_ID, ROLE_ID, PERMISSION_ID,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('MAY.SEQ_ROLE_PERMISSION_HIS'), NEW.ID, NEW.ROLE_ID, NEW.PERMISSION_ID,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'UPDATE', NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO MAY.ROLE_PERMISSION_HIS (
            ID, ORIGINAL_ID, ROLE_ID, PERMISSION_ID,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('MAY.SEQ_ROLE_PERMISSION_HIS'), OLD.ID, OLD.ROLE_ID, OLD.PERMISSION_ID,
            OLD.CREATED_BY, OLD.CREATED_DATE, OLD.CREATED_IP, OLD.UPDATED_BY, OLD.UPDATED_DATE, OLD.UPDATED_IP,
            'DELETE', COALESCE(OLD.UPDATED_BY, OLD.CREATED_BY), COALESCE(OLD.UPDATED_DATE, OLD.CREATED_DATE), COALESCE(OLD.UPDATED_IP, OLD.CREATED_IP)
        );
        RETURN OLD;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRG_ROLE_PERMISSION_HIS
    AFTER INSERT OR UPDATE OR DELETE ON MAY.ROLE_PERMISSION
    FOR EACH ROW EXECUTE FUNCTION MAY.FN_ROLE_PERMISSION_HIS();


-- =============================================================
-- 10. GRANTS
-- =============================================================
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'MAY_APP') THEN
        CREATE ROLE MAY_APP WITH LOGIN PASSWORD '123456789';
    END IF;
END
$$;

GRANT USAGE ON SCHEMA MAY TO MAY_APP;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA MAY TO MAY_APP;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA MAY TO MAY_APP;

ALTER DEFAULT PRIVILEGES IN SCHEMA MAY GRANT ALL ON TABLES    TO MAY_APP;
ALTER DEFAULT PRIVILEGES IN SCHEMA MAY GRANT ALL ON SEQUENCES TO MAY_APP;


-- =============================================================
-- 11. SEED DATA
-- =============================================================

-- PERMISSIONS
INSERT INTO MAY.PERMISSION (ID, NAME, DESCRIPTION, MODULE, ACTION, STATUS, CREATED_BY, CREATED_DATE, CREATED_IP)
VALUES
    -- USER
    (nextval('MAY.SEQ_PERMISSION'), 'USER_READ',             'Kullanici goruntuleme yetkisi',    'USER',        'READ',   'ACTIVE', 'SYSTEM', NOW(), '127.0.0.1'),
    (nextval('MAY.SEQ_PERMISSION'), 'USER_CREATE',           'Kullanici olusturma yetkisi',      'USER',        'CREATE', 'ACTIVE', 'SYSTEM', NOW(), '127.0.0.1'),
    (nextval('MAY.SEQ_PERMISSION'), 'USER_UPDATE',           'Kullanici guncelleme yetkisi',     'USER',        'UPDATE', 'ACTIVE', 'SYSTEM', NOW(), '127.0.0.1'),
    (nextval('MAY.SEQ_PERMISSION'), 'USER_DELETE',           'Kullanici silme yetkisi',          'USER',        'DELETE', 'ACTIVE', 'SYSTEM', NOW(), '127.0.0.1'),
    -- ROLES
    (nextval('MAY.SEQ_PERMISSION'), 'ROLES_READ',            'Rol goruntuleme yetkisi',          'ROLES',       'READ',   'ACTIVE', 'SYSTEM', NOW(), '127.0.0.1'),
    (nextval('MAY.SEQ_PERMISSION'), 'ROLES_CREATE',          'Rol olusturma yetkisi',            'ROLES',       'CREATE', 'ACTIVE', 'SYSTEM', NOW(), '127.0.0.1'),
    (nextval('MAY.SEQ_PERMISSION'), 'ROLES_UPDATE',          'Rol guncelleme yetkisi',           'ROLES',       'UPDATE', 'ACTIVE', 'SYSTEM', NOW(), '127.0.0.1'),
    (nextval('MAY.SEQ_PERMISSION'), 'ROLES_DELETE',          'Rol silme yetkisi',                'ROLES',       'DELETE', 'ACTIVE', 'SYSTEM', NOW(), '127.0.0.1'),
    -- PERMISSION
    (nextval('MAY.SEQ_PERMISSION'), 'PERMISSION_READ',       'Yetki goruntuleme yetkisi',        'PERMISSION',  'READ',   'ACTIVE', 'SYSTEM', NOW(), '127.0.0.1'),
    (nextval('MAY.SEQ_PERMISSION'), 'PERMISSION_CREATE',     'Yetki olusturma yetkisi',          'PERMISSION',  'CREATE', 'ACTIVE', 'SYSTEM', NOW(), '127.0.0.1'),
    (nextval('MAY.SEQ_PERMISSION'), 'PERMISSION_UPDATE',     'Yetki guncelleme yetkisi',         'PERMISSION',  'UPDATE', 'ACTIVE', 'SYSTEM', NOW(), '127.0.0.1'),
    (nextval('MAY.SEQ_PERMISSION'), 'PERMISSION_DELETE',     'Yetki silme yetkisi',              'PERMISSION',  'DELETE', 'ACTIVE', 'SYSTEM', NOW(), '127.0.0.1');

-- ROLES
INSERT INTO MAY.ROLE (ID, NAME, DESCRIPTION, STATUS, CREATED_BY, CREATED_DATE, CREATED_IP)
VALUES
    (nextval('MAY.SEQ_ROLE'), 'ADMIN',  'Tum yetkilere sahip yonetici rolu',       'ACTIVE', 'SYSTEM', NOW(), '127.0.0.1'),
    (nextval('MAY.SEQ_ROLE'), 'VIEWER', 'Sadece goruntuleme yetkisine sahip rol',   'ACTIVE', 'SYSTEM', NOW(), '127.0.0.1');

-- USERS
INSERT INTO MAY.USERS (ID, USERNAME, EMAIL, PASSWORD_HASH, FIRST_NAME, LAST_NAME, PHONE, STATUS, CREATED_BY, CREATED_DATE, CREATED_IP)
VALUES
    (nextval('MAY.SEQ_USERS'), 'admin', 'admin@may.com', '$2b$10$FOLJ0NEccXwiE/IE98Gs6ug6a7aS.CVyMuiIkOHfngBTlDc8UTSIG', 'Admin', 'User', '+905551112233', 'ACTIVE', 'SYSTEM', NOW(), '127.0.0.1');

-- ROLE_PERMISSION: ADMIN tum yetkiler
INSERT INTO MAY.ROLE_PERMISSION (ID, ROLE_ID, PERMISSION_ID, CREATED_BY, CREATED_DATE, CREATED_IP)
SELECT
    nextval('MAY.SEQ_ROLE_PERMISSION'),
    (SELECT ID FROM MAY.ROLE WHERE NAME = 'ADMIN'),
    p.ID,
    'SYSTEM',
    NOW(),
    '127.0.0.1'
FROM MAY.PERMISSION p;

-- ROLE_PERMISSION: VIEWER sadece READ yetkiler
INSERT INTO MAY.ROLE_PERMISSION (ID, ROLE_ID, PERMISSION_ID, CREATED_BY, CREATED_DATE, CREATED_IP)
SELECT
    nextval('MAY.SEQ_ROLE_PERMISSION'),
    (SELECT ID FROM MAY.ROLE WHERE NAME = 'VIEWER'),
    p.ID,
    'SYSTEM',
    NOW(),
    '127.0.0.1'
FROM MAY.PERMISSION p
WHERE p.ACTION = 'READ';

-- USERS_ROLE: admin kullanicisina ADMIN rolu
INSERT INTO MAY.USERS_ROLE (ID, USERS_ID, ROLE_ID, ASSIGNED_BY, ASSIGNED_DATE, CREATED_BY, CREATED_DATE, CREATED_IP)
SELECT
    nextval('MAY.SEQ_USERS_ROLE'),
    (SELECT ID FROM MAY.USERS WHERE USERNAME = 'admin'),
    (SELECT ID FROM MAY.ROLE WHERE NAME = 'ADMIN'),
    'SYSTEM',
    NOW(),
    'SYSTEM',
    NOW(),
    '127.0.0.1';
