-- =============================================================
-- 6. MODULE
-- =============================================================
CREATE SEQUENCE MAY.SEQ_MODULE START WITH 1 INCREMENT BY 1;

CREATE TABLE MAY.MODULE (
    ID              BIGINT          NOT NULL DEFAULT nextval('MAY.SEQ_MODULE'),
    NAME            VARCHAR(200)    NOT NULL,
    BRAND           VARCHAR(100)    NOT NULL,
    MODEL           VARCHAR(100)    NOT NULL,
    YEAR            INTEGER,
    CODE            VARCHAR(100)    NOT NULL,
    STATUS          VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    CREATED_BY      VARCHAR(100)    NOT NULL,
    CREATED_DATE    TIMESTAMP       NOT NULL,
    CREATED_IP      VARCHAR(45)     NOT NULL,
    UPDATED_BY      VARCHAR(100),
    UPDATED_DATE    TIMESTAMP,
    UPDATED_IP      VARCHAR(45),
    CONSTRAINT PK_MODULE        PRIMARY KEY (ID),
    CONSTRAINT CK_MODULE_STATUS CHECK (STATUS IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX IDX_MODULE_NAME   ON MAY.MODULE (NAME);
CREATE INDEX IDX_MODULE_BRAND  ON MAY.MODULE (BRAND);
CREATE INDEX IDX_MODULE_MODEL  ON MAY.MODULE (MODEL);
CREATE INDEX IDX_MODULE_CODE   ON MAY.MODULE (CODE);
CREATE INDEX IDX_MODULE_STATUS ON MAY.MODULE (STATUS);

CREATE SEQUENCE MAY.SEQ_MODULE_HIS START WITH 1 INCREMENT BY 1;

CREATE TABLE MAY.MODULE_HIS (
    ID              BIGINT          NOT NULL DEFAULT nextval('MAY.SEQ_MODULE_HIS'),
    ORIGINAL_ID     BIGINT          NOT NULL,
    NAME            VARCHAR(200)    NOT NULL,
    BRAND           VARCHAR(100)    NOT NULL,
    MODEL           VARCHAR(100)    NOT NULL,
    YEAR            INTEGER,
    CODE            VARCHAR(100)    NOT NULL,
    STATUS          VARCHAR(20)     NOT NULL,
    CREATED_BY      VARCHAR(100)    NOT NULL,
    CREATED_DATE    TIMESTAMP       NOT NULL,
    CREATED_IP      VARCHAR(45)     NOT NULL,
    UPDATED_BY      VARCHAR(100),
    UPDATED_DATE    TIMESTAMP,
    UPDATED_IP      VARCHAR(45),
    DML_OPERATION   VARCHAR(10),
    DML_BY          VARCHAR(100),
    DML_DATE        TIMESTAMP,
    DML_IP          VARCHAR(45),
    CONSTRAINT PK_MODULE_HIS PRIMARY KEY (ID)
);

CREATE INDEX IDX_MODULE_HIS_ORIGINAL_ID ON MAY.MODULE_HIS (ORIGINAL_ID);

CREATE OR REPLACE FUNCTION MAY.FN_MODULE_HIS()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO MAY.MODULE_HIS (
            ID, ORIGINAL_ID, NAME, BRAND, MODEL, YEAR, CODE, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('MAY.SEQ_MODULE_HIS'), NEW.ID, NEW.NAME, NEW.BRAND, NEW.MODEL, NEW.YEAR, NEW.CODE, NEW.STATUS,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'INSERT', NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO MAY.MODULE_HIS (
            ID, ORIGINAL_ID, NAME, BRAND, MODEL, YEAR, CODE, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('MAY.SEQ_MODULE_HIS'), NEW.ID, NEW.NAME, NEW.BRAND, NEW.MODEL, NEW.YEAR, NEW.CODE, NEW.STATUS,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'UPDATE', NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO MAY.MODULE_HIS (
            ID, ORIGINAL_ID, NAME, BRAND, MODEL, YEAR, CODE, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('MAY.SEQ_MODULE_HIS'), OLD.ID, OLD.NAME, OLD.BRAND, OLD.MODEL, OLD.YEAR, OLD.CODE, OLD.STATUS,
            OLD.CREATED_BY, OLD.CREATED_DATE, OLD.CREATED_IP, OLD.UPDATED_BY, OLD.UPDATED_DATE, OLD.UPDATED_IP,
            'DELETE', COALESCE(OLD.UPDATED_BY, OLD.CREATED_BY), COALESCE(OLD.UPDATED_DATE, OLD.CREATED_DATE), COALESCE(OLD.UPDATED_IP, OLD.CREATED_IP)
        );
        RETURN OLD;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRG_MODULE_HIS
    AFTER INSERT OR UPDATE OR DELETE ON MAY.MODULE
    FOR EACH ROW EXECUTE FUNCTION MAY.FN_MODULE_HIS();


-- =============================================================
-- 7. ANALYSIS
-- =============================================================
CREATE SEQUENCE MAY.SEQ_ANALYSIS START WITH 1 INCREMENT BY 1;

CREATE TABLE MAY.ANALYSIS (
    ID              BIGINT          NOT NULL DEFAULT nextval('MAY.SEQ_ANALYSIS'),
    NAME            VARCHAR(200)    NOT NULL,
    DESCRIPTION     VARCHAR(500),
    MODULE_ID       BIGINT          NOT NULL,
    NOTE            VARCHAR(1000),
    STATUS          VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    CREATED_BY      VARCHAR(100)    NOT NULL,
    CREATED_DATE    TIMESTAMP       NOT NULL,
    CREATED_IP      VARCHAR(45)     NOT NULL,
    UPDATED_BY      VARCHAR(100),
    UPDATED_DATE    TIMESTAMP,
    UPDATED_IP      VARCHAR(45),
    CONSTRAINT PK_ANALYSIS          PRIMARY KEY (ID),
    CONSTRAINT FK_ANALYSIS_MODULE   FOREIGN KEY (MODULE_ID) REFERENCES MAY.MODULE(ID),
    CONSTRAINT CK_ANALYSIS_STATUS   CHECK (STATUS IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX IDX_ANALYSIS_NAME      ON MAY.ANALYSIS (NAME);
CREATE INDEX IDX_ANALYSIS_MODULE_ID ON MAY.ANALYSIS (MODULE_ID);
CREATE INDEX IDX_ANALYSIS_STATUS    ON MAY.ANALYSIS (STATUS);

CREATE SEQUENCE MAY.SEQ_ANALYSIS_HIS START WITH 1 INCREMENT BY 1;

CREATE TABLE MAY.ANALYSIS_HIS (
    ID              BIGINT          NOT NULL DEFAULT nextval('MAY.SEQ_ANALYSIS_HIS'),
    ORIGINAL_ID     BIGINT          NOT NULL,
    NAME            VARCHAR(200)    NOT NULL,
    DESCRIPTION     VARCHAR(500),
    MODULE_ID       BIGINT          NOT NULL,
    NOTE            VARCHAR(1000),
    STATUS          VARCHAR(20)     NOT NULL,
    CREATED_BY      VARCHAR(100)    NOT NULL,
    CREATED_DATE    TIMESTAMP       NOT NULL,
    CREATED_IP      VARCHAR(45)     NOT NULL,
    UPDATED_BY      VARCHAR(100),
    UPDATED_DATE    TIMESTAMP,
    UPDATED_IP      VARCHAR(45),
    DML_OPERATION   VARCHAR(10),
    DML_BY          VARCHAR(100),
    DML_DATE        TIMESTAMP,
    DML_IP          VARCHAR(45),
    CONSTRAINT PK_ANALYSIS_HIS PRIMARY KEY (ID)
);

CREATE INDEX IDX_ANALYSIS_HIS_ORIGINAL_ID ON MAY.ANALYSIS_HIS (ORIGINAL_ID);

CREATE OR REPLACE FUNCTION MAY.FN_ANALYSIS_HIS()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO MAY.ANALYSIS_HIS (
            ID, ORIGINAL_ID, NAME, DESCRIPTION, MODULE_ID, NOTE, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('MAY.SEQ_ANALYSIS_HIS'), NEW.ID, NEW.NAME, NEW.DESCRIPTION, NEW.MODULE_ID, NEW.NOTE, NEW.STATUS,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'INSERT', NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO MAY.ANALYSIS_HIS (
            ID, ORIGINAL_ID, NAME, DESCRIPTION, MODULE_ID, NOTE, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('MAY.SEQ_ANALYSIS_HIS'), NEW.ID, NEW.NAME, NEW.DESCRIPTION, NEW.MODULE_ID, NEW.NOTE, NEW.STATUS,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'UPDATE', NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO MAY.ANALYSIS_HIS (
            ID, ORIGINAL_ID, NAME, DESCRIPTION, MODULE_ID, NOTE, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('MAY.SEQ_ANALYSIS_HIS'), OLD.ID, OLD.NAME, OLD.DESCRIPTION, OLD.MODULE_ID, OLD.NOTE, OLD.STATUS,
            OLD.CREATED_BY, OLD.CREATED_DATE, OLD.CREATED_IP, OLD.UPDATED_BY, OLD.UPDATED_DATE, OLD.UPDATED_IP,
            'DELETE', COALESCE(OLD.UPDATED_BY, OLD.CREATED_BY), COALESCE(OLD.UPDATED_DATE, OLD.CREATED_DATE), COALESCE(OLD.UPDATED_IP, OLD.CREATED_IP)
        );
        RETURN OLD;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRG_ANALYSIS_HIS
    AFTER INSERT OR UPDATE OR DELETE ON MAY.ANALYSIS
    FOR EACH ROW EXECUTE FUNCTION MAY.FN_ANALYSIS_HIS();


-- =============================================================
-- 8. TEST
-- =============================================================
CREATE SEQUENCE MAY.SEQ_TEST START WITH 1 INCREMENT BY 1;

CREATE TABLE MAY.TEST (
    ID              BIGINT          NOT NULL DEFAULT nextval('MAY.SEQ_TEST'),
    NAME            VARCHAR(200)    NOT NULL,
    DESCRIPTION     VARCHAR(500),
    MODULE_ID       BIGINT          NOT NULL,
    NOTE            VARCHAR(1000),
    STATUS          VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    CREATED_BY      VARCHAR(100)    NOT NULL,
    CREATED_DATE    TIMESTAMP       NOT NULL,
    CREATED_IP      VARCHAR(45)     NOT NULL,
    UPDATED_BY      VARCHAR(100),
    UPDATED_DATE    TIMESTAMP,
    UPDATED_IP      VARCHAR(45),
    CONSTRAINT PK_TEST          PRIMARY KEY (ID),
    CONSTRAINT FK_TEST_MODULE   FOREIGN KEY (MODULE_ID) REFERENCES MAY.MODULE(ID),
    CONSTRAINT CK_TEST_STATUS   CHECK (STATUS IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX IDX_TEST_NAME      ON MAY.TEST (NAME);
CREATE INDEX IDX_TEST_MODULE_ID ON MAY.TEST (MODULE_ID);
CREATE INDEX IDX_TEST_STATUS    ON MAY.TEST (STATUS);

CREATE SEQUENCE MAY.SEQ_TEST_HIS START WITH 1 INCREMENT BY 1;

CREATE TABLE MAY.TEST_HIS (
    ID              BIGINT          NOT NULL DEFAULT nextval('MAY.SEQ_TEST_HIS'),
    ORIGINAL_ID     BIGINT          NOT NULL,
    NAME            VARCHAR(200)    NOT NULL,
    DESCRIPTION     VARCHAR(500),
    MODULE_ID       BIGINT          NOT NULL,
    NOTE            VARCHAR(1000),
    STATUS          VARCHAR(20)     NOT NULL,
    CREATED_BY      VARCHAR(100)    NOT NULL,
    CREATED_DATE    TIMESTAMP       NOT NULL,
    CREATED_IP      VARCHAR(45)     NOT NULL,
    UPDATED_BY      VARCHAR(100),
    UPDATED_DATE    TIMESTAMP,
    UPDATED_IP      VARCHAR(45),
    DML_OPERATION   VARCHAR(10),
    DML_BY          VARCHAR(100),
    DML_DATE        TIMESTAMP,
    DML_IP          VARCHAR(45),
    CONSTRAINT PK_TEST_HIS PRIMARY KEY (ID)
);

CREATE INDEX IDX_TEST_HIS_ORIGINAL_ID ON MAY.TEST_HIS (ORIGINAL_ID);

CREATE OR REPLACE FUNCTION MAY.FN_TEST_HIS()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO MAY.TEST_HIS (
            ID, ORIGINAL_ID, NAME, DESCRIPTION, MODULE_ID, NOTE, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('MAY.SEQ_TEST_HIS'), NEW.ID, NEW.NAME, NEW.DESCRIPTION, NEW.MODULE_ID, NEW.NOTE, NEW.STATUS,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'INSERT', NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO MAY.TEST_HIS (
            ID, ORIGINAL_ID, NAME, DESCRIPTION, MODULE_ID, NOTE, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('MAY.SEQ_TEST_HIS'), NEW.ID, NEW.NAME, NEW.DESCRIPTION, NEW.MODULE_ID, NEW.NOTE, NEW.STATUS,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'UPDATE', NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO MAY.TEST_HIS (
            ID, ORIGINAL_ID, NAME, DESCRIPTION, MODULE_ID, NOTE, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('MAY.SEQ_TEST_HIS'), OLD.ID, OLD.NAME, OLD.DESCRIPTION, OLD.MODULE_ID, OLD.NOTE, OLD.STATUS,
            OLD.CREATED_BY, OLD.CREATED_DATE, OLD.CREATED_IP, OLD.UPDATED_BY, OLD.UPDATED_DATE, OLD.UPDATED_IP,
            'DELETE', COALESCE(OLD.UPDATED_BY, OLD.CREATED_BY), COALESCE(OLD.UPDATED_DATE, OLD.CREATED_DATE), COALESCE(OLD.UPDATED_IP, OLD.CREATED_IP)
        );
        RETURN OLD;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRG_TEST_HIS
    AFTER INSERT OR UPDATE OR DELETE ON MAY.TEST
    FOR EACH ROW EXECUTE FUNCTION MAY.FN_TEST_HIS();


-- =============================================================
-- GRANTS
-- =============================================================
GRANT ALL PRIVILEGES ON MAY.MODULE TO MAY_APP;
GRANT ALL PRIVILEGES ON MAY.MODULE_HIS TO MAY_APP;
GRANT ALL PRIVILEGES ON MAY.SEQ_MODULE TO MAY_APP;
GRANT ALL PRIVILEGES ON MAY.SEQ_MODULE_HIS TO MAY_APP;

GRANT ALL PRIVILEGES ON MAY.ANALYSIS TO MAY_APP;
GRANT ALL PRIVILEGES ON MAY.ANALYSIS_HIS TO MAY_APP;
GRANT ALL PRIVILEGES ON MAY.SEQ_ANALYSIS TO MAY_APP;
GRANT ALL PRIVILEGES ON MAY.SEQ_ANALYSIS_HIS TO MAY_APP;

GRANT ALL PRIVILEGES ON MAY.TEST TO MAY_APP;
GRANT ALL PRIVILEGES ON MAY.TEST_HIS TO MAY_APP;
GRANT ALL PRIVILEGES ON MAY.SEQ_TEST TO MAY_APP;
GRANT ALL PRIVILEGES ON MAY.SEQ_TEST_HIS TO MAY_APP;


-- =============================================================
-- SEED DATA - PERMISSIONS
-- =============================================================
INSERT INTO MAY.PERMISSION (ID, NAME, DESCRIPTION, MODULE, ACTION, STATUS, CREATED_BY, CREATED_DATE, CREATED_IP)
VALUES
    -- MODULE
    (nextval('MAY.SEQ_PERMISSION'), 'MODULE_READ',       'Modul goruntuleme yetkisi',    'MODULE',    'READ',   'ACTIVE', 'SYSTEM', NOW(), '127.0.0.1'),
    (nextval('MAY.SEQ_PERMISSION'), 'MODULE_CREATE',     'Modul olusturma yetkisi',      'MODULE',    'CREATE', 'ACTIVE', 'SYSTEM', NOW(), '127.0.0.1'),
    (nextval('MAY.SEQ_PERMISSION'), 'MODULE_UPDATE',     'Modul guncelleme yetkisi',     'MODULE',    'UPDATE', 'ACTIVE', 'SYSTEM', NOW(), '127.0.0.1'),
    (nextval('MAY.SEQ_PERMISSION'), 'MODULE_DELETE',     'Modul silme yetkisi',          'MODULE',    'DELETE', 'ACTIVE', 'SYSTEM', NOW(), '127.0.0.1'),
    -- ANALYSIS
    (nextval('MAY.SEQ_PERMISSION'), 'ANALYSIS_READ',     'Analiz goruntuleme yetkisi',   'ANALYSIS',  'READ',   'ACTIVE', 'SYSTEM', NOW(), '127.0.0.1'),
    (nextval('MAY.SEQ_PERMISSION'), 'ANALYSIS_CREATE',   'Analiz olusturma yetkisi',     'ANALYSIS',  'CREATE', 'ACTIVE', 'SYSTEM', NOW(), '127.0.0.1'),
    (nextval('MAY.SEQ_PERMISSION'), 'ANALYSIS_UPDATE',   'Analiz guncelleme yetkisi',    'ANALYSIS',  'UPDATE', 'ACTIVE', 'SYSTEM', NOW(), '127.0.0.1'),
    (nextval('MAY.SEQ_PERMISSION'), 'ANALYSIS_DELETE',   'Analiz silme yetkisi',         'ANALYSIS',  'DELETE', 'ACTIVE', 'SYSTEM', NOW(), '127.0.0.1'),
    -- TEST
    (nextval('MAY.SEQ_PERMISSION'), 'TEST_READ',         'Test goruntuleme yetkisi',     'TEST',      'READ',   'ACTIVE', 'SYSTEM', NOW(), '127.0.0.1'),
    (nextval('MAY.SEQ_PERMISSION'), 'TEST_CREATE',       'Test olusturma yetkisi',       'TEST',      'CREATE', 'ACTIVE', 'SYSTEM', NOW(), '127.0.0.1'),
    (nextval('MAY.SEQ_PERMISSION'), 'TEST_UPDATE',       'Test guncelleme yetkisi',      'TEST',      'UPDATE', 'ACTIVE', 'SYSTEM', NOW(), '127.0.0.1'),
    (nextval('MAY.SEQ_PERMISSION'), 'TEST_DELETE',       'Test silme yetkisi',           'TEST',      'DELETE', 'ACTIVE', 'SYSTEM', NOW(), '127.0.0.1');

-- ROLE_PERMISSION: ADMIN - yeni yetkiler
INSERT INTO MAY.ROLE_PERMISSION (ID, ROLE_ID, PERMISSION_ID, CREATED_BY, CREATED_DATE, CREATED_IP)
SELECT
    nextval('MAY.SEQ_ROLE_PERMISSION'),
    (SELECT ID FROM MAY.ROLE WHERE NAME = 'ADMIN'),
    p.ID,
    'SYSTEM',
    NOW(),
    '127.0.0.1'
FROM MAY.PERMISSION p
WHERE p.MODULE IN ('MODULE', 'ANALYSIS', 'TEST');
