-- =============================================================
-- May Database - User Session Management
-- =============================================================

-- =============================================================
-- 1. USER_SESSION
-- =============================================================
CREATE SEQUENCE MAY.SEQ_USER_SESSION START WITH 1 INCREMENT BY 1;

CREATE TABLE MAY.USER_SESSION (
    ID                      BIGINT          NOT NULL DEFAULT nextval('MAY.SEQ_USER_SESSION'),
    USERS_ID                BIGINT          NOT NULL,
    REFRESH_TOKEN_HASH      VARCHAR(64)     NOT NULL,
    PLATFORM                VARCHAR(20)     NOT NULL,
    DEVICE_INFO             VARCHAR(500),
    IP_ADDRESS              VARCHAR(45)     NOT NULL,
    LOGIN_DATE              TIMESTAMP       NOT NULL,
    LAST_ACTIVITY_DATE      TIMESTAMP       NOT NULL,
    EXPIRES_AT              TIMESTAMP       NOT NULL,
    STATUS                  VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    CREATED_BY              VARCHAR(100)    NOT NULL,
    CREATED_DATE            TIMESTAMP       NOT NULL,
    CREATED_IP              VARCHAR(45)     NOT NULL,
    UPDATED_BY              VARCHAR(100),
    UPDATED_DATE            TIMESTAMP,
    UPDATED_IP              VARCHAR(45),
    CONSTRAINT PK_USER_SESSION              PRIMARY KEY (ID),
    CONSTRAINT FK_USER_SESSION_USERS        FOREIGN KEY (USERS_ID) REFERENCES MAY.USERS(ID),
    CONSTRAINT UK_USER_SESSION_TOKEN_HASH   UNIQUE (REFRESH_TOKEN_HASH),
    CONSTRAINT CK_USER_SESSION_PLATFORM     CHECK (PLATFORM IN ('WEB', 'MOBILE')),
    CONSTRAINT CK_USER_SESSION_STATUS       CHECK (STATUS IN ('ACTIVE', 'REVOKED', 'EXPIRED'))
);

CREATE INDEX IDX_USER_SESSION_USERS_ID   ON MAY.USER_SESSION (USERS_ID);
CREATE INDEX IDX_USER_SESSION_PLATFORM   ON MAY.USER_SESSION (USERS_ID, PLATFORM);
CREATE INDEX IDX_USER_SESSION_STATUS     ON MAY.USER_SESSION (STATUS);
CREATE INDEX IDX_USER_SESSION_EXPIRES_AT ON MAY.USER_SESSION (EXPIRES_AT);

-- =============================================================
-- 2. USER_SESSION_HIS
-- =============================================================
CREATE SEQUENCE MAY.SEQ_USER_SESSION_HIS START WITH 1 INCREMENT BY 1;

CREATE TABLE MAY.USER_SESSION_HIS (
    ID                      BIGINT          NOT NULL DEFAULT nextval('MAY.SEQ_USER_SESSION_HIS'),
    ORIGINAL_ID             BIGINT          NOT NULL,
    USERS_ID                BIGINT          NOT NULL,
    REFRESH_TOKEN_HASH      VARCHAR(64)     NOT NULL,
    PLATFORM                VARCHAR(20)     NOT NULL,
    DEVICE_INFO             VARCHAR(500),
    IP_ADDRESS              VARCHAR(45)     NOT NULL,
    LOGIN_DATE              TIMESTAMP       NOT NULL,
    LAST_ACTIVITY_DATE      TIMESTAMP       NOT NULL,
    EXPIRES_AT              TIMESTAMP       NOT NULL,
    STATUS                  VARCHAR(20)     NOT NULL,
    CREATED_BY              VARCHAR(100)    NOT NULL,
    CREATED_DATE            TIMESTAMP       NOT NULL,
    CREATED_IP              VARCHAR(45)     NOT NULL,
    UPDATED_BY              VARCHAR(100),
    UPDATED_DATE            TIMESTAMP,
    UPDATED_IP              VARCHAR(45),
    DML_OPERATION           VARCHAR(10),
    DML_BY                  VARCHAR(100),
    DML_DATE                TIMESTAMP,
    DML_IP                  VARCHAR(45),
    CONSTRAINT PK_USER_SESSION_HIS PRIMARY KEY (ID)
);

CREATE INDEX IDX_USER_SESSION_HIS_ORIGINAL_ID ON MAY.USER_SESSION_HIS (ORIGINAL_ID);

CREATE OR REPLACE FUNCTION MAY.FN_USER_SESSION_HIS()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO MAY.USER_SESSION_HIS (
            ID, ORIGINAL_ID, USERS_ID, REFRESH_TOKEN_HASH, PLATFORM, DEVICE_INFO,
            IP_ADDRESS, LOGIN_DATE, LAST_ACTIVITY_DATE, EXPIRES_AT, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('MAY.SEQ_USER_SESSION_HIS'), NEW.ID, NEW.USERS_ID, NEW.REFRESH_TOKEN_HASH, NEW.PLATFORM, NEW.DEVICE_INFO,
            NEW.IP_ADDRESS, NEW.LOGIN_DATE, NEW.LAST_ACTIVITY_DATE, NEW.EXPIRES_AT, NEW.STATUS,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'INSERT', NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO MAY.USER_SESSION_HIS (
            ID, ORIGINAL_ID, USERS_ID, REFRESH_TOKEN_HASH, PLATFORM, DEVICE_INFO,
            IP_ADDRESS, LOGIN_DATE, LAST_ACTIVITY_DATE, EXPIRES_AT, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('MAY.SEQ_USER_SESSION_HIS'), NEW.ID, NEW.USERS_ID, NEW.REFRESH_TOKEN_HASH, NEW.PLATFORM, NEW.DEVICE_INFO,
            NEW.IP_ADDRESS, NEW.LOGIN_DATE, NEW.LAST_ACTIVITY_DATE, NEW.EXPIRES_AT, NEW.STATUS,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'UPDATE', NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO MAY.USER_SESSION_HIS (
            ID, ORIGINAL_ID, USERS_ID, REFRESH_TOKEN_HASH, PLATFORM, DEVICE_INFO,
            IP_ADDRESS, LOGIN_DATE, LAST_ACTIVITY_DATE, EXPIRES_AT, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('MAY.SEQ_USER_SESSION_HIS'), OLD.ID, OLD.USERS_ID, OLD.REFRESH_TOKEN_HASH, OLD.PLATFORM, OLD.DEVICE_INFO,
            OLD.IP_ADDRESS, OLD.LOGIN_DATE, OLD.LAST_ACTIVITY_DATE, OLD.EXPIRES_AT, OLD.STATUS,
            OLD.CREATED_BY, OLD.CREATED_DATE, OLD.CREATED_IP, OLD.UPDATED_BY, OLD.UPDATED_DATE, OLD.UPDATED_IP,
            'DELETE', COALESCE(OLD.UPDATED_BY, OLD.CREATED_BY), COALESCE(OLD.UPDATED_DATE, OLD.CREATED_DATE), COALESCE(OLD.UPDATED_IP, OLD.CREATED_IP)
        );
        RETURN OLD;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRG_USER_SESSION_HIS
    AFTER INSERT OR UPDATE OR DELETE ON MAY.USER_SESSION
    FOR EACH ROW EXECUTE FUNCTION MAY.FN_USER_SESSION_HIS();
