-- =============================================================
-- 9. SERVICE
-- =============================================================
CREATE SEQUENCE MAY.SEQ_SERVICE START WITH 1 INCREMENT BY 1;

CREATE TABLE MAY.SERVICE (
    ID              BIGINT          NOT NULL DEFAULT nextval('MAY.SEQ_SERVICE'),
    NAME            VARCHAR(200)    NOT NULL,
    CITY            VARCHAR(100),
    TOWN            VARCHAR(100),
    ADDRESS         VARCHAR(500),
    STATUS          VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    CREATED_BY      VARCHAR(100)    NOT NULL,
    CREATED_DATE    TIMESTAMP       NOT NULL,
    CREATED_IP      VARCHAR(45)     NOT NULL,
    UPDATED_BY      VARCHAR(100),
    UPDATED_DATE    TIMESTAMP,
    UPDATED_IP      VARCHAR(45),
    CONSTRAINT PK_SERVICE        PRIMARY KEY (ID),
    CONSTRAINT CK_SERVICE_STATUS CHECK (STATUS IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX IDX_SERVICE_NAME   ON MAY.SERVICE (NAME);
CREATE INDEX IDX_SERVICE_CITY   ON MAY.SERVICE (CITY);
CREATE INDEX IDX_SERVICE_TOWN   ON MAY.SERVICE (TOWN);
CREATE INDEX IDX_SERVICE_STATUS ON MAY.SERVICE (STATUS);

CREATE SEQUENCE MAY.SEQ_SERVICE_HIS START WITH 1 INCREMENT BY 1;

CREATE TABLE MAY.SERVICE_HIS (
    ID              BIGINT          NOT NULL DEFAULT nextval('MAY.SEQ_SERVICE_HIS'),
    ORIGINAL_ID     BIGINT          NOT NULL,
    NAME            VARCHAR(200)    NOT NULL,
    CITY            VARCHAR(100),
    TOWN            VARCHAR(100),
    ADDRESS         VARCHAR(500),
    STATUS          VARCHAR(20)     NOT NULL,
    CREATED_BY      VARCHAR(100)    NOT NULL,
    CREATED_DATE    TIMESTAMP       NOT NULL,
    CREATED_IP      VARCHAR(45)     NOT NULL,
    UPDATED_BY      VARCHAR(100),
    UPDATED_DATE    TIMESTAMP,
    UPDATED_IP      VARCHAR(45),
    DML_OPERATION   VARCHAR(10),
    DML_BY          VARCHAR(100),
    DML_DATE        TIMESTAMP,
    DML_IP          VARCHAR(45),
    CONSTRAINT PK_SERVICE_HIS PRIMARY KEY (ID)
);

CREATE INDEX IDX_SERVICE_HIS_ORIGINAL_ID ON MAY.SERVICE_HIS (ORIGINAL_ID);

CREATE OR REPLACE FUNCTION MAY.FN_SERVICE_HIS()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO MAY.SERVICE_HIS (
            ID, ORIGINAL_ID, NAME, CITY, TOWN, ADDRESS, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('MAY.SEQ_SERVICE_HIS'), NEW.ID, NEW.NAME, NEW.CITY, NEW.TOWN, NEW.ADDRESS, NEW.STATUS,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'INSERT', NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO MAY.SERVICE_HIS (
            ID, ORIGINAL_ID, NAME, CITY, TOWN, ADDRESS, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('MAY.SEQ_SERVICE_HIS'), NEW.ID, NEW.NAME, NEW.CITY, NEW.TOWN, NEW.ADDRESS, NEW.STATUS,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'UPDATE', NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO MAY.SERVICE_HIS (
            ID, ORIGINAL_ID, NAME, CITY, TOWN, ADDRESS, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('MAY.SEQ_SERVICE_HIS'), OLD.ID, OLD.NAME, OLD.CITY, OLD.TOWN, OLD.ADDRESS, OLD.STATUS,
            OLD.CREATED_BY, OLD.CREATED_DATE, OLD.CREATED_IP, OLD.UPDATED_BY, OLD.UPDATED_DATE, OLD.UPDATED_IP,
            'DELETE', COALESCE(OLD.UPDATED_BY, OLD.CREATED_BY), COALESCE(OLD.UPDATED_DATE, OLD.CREATED_DATE), COALESCE(OLD.UPDATED_IP, OLD.CREATED_IP)
        );
        RETURN OLD;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRG_SERVICE_HIS
    AFTER INSERT OR UPDATE OR DELETE ON MAY.SERVICE
    FOR EACH ROW EXECUTE FUNCTION MAY.FN_SERVICE_HIS();


-- =============================================================
-- GRANTS
-- =============================================================
GRANT ALL PRIVILEGES ON MAY.SERVICE TO MAY_APP;
GRANT ALL PRIVILEGES ON MAY.SERVICE_HIS TO MAY_APP;
GRANT ALL PRIVILEGES ON MAY.SEQ_SERVICE TO MAY_APP;
GRANT ALL PRIVILEGES ON MAY.SEQ_SERVICE_HIS TO MAY_APP;


-- =============================================================
-- SEED DATA - PERMISSIONS
-- =============================================================
INSERT INTO MAY.PERMISSION (ID, NAME, DESCRIPTION, MODULE, ACTION, STATUS, CREATED_BY, CREATED_DATE, CREATED_IP)
VALUES
    (nextval('MAY.SEQ_PERMISSION'), 'SERVICE_READ',     'Servis goruntuleme yetkisi',   'SERVICE',  'READ',   'ACTIVE', 'SYSTEM', NOW(), '127.0.0.1'),
    (nextval('MAY.SEQ_PERMISSION'), 'SERVICE_CREATE',   'Servis olusturma yetkisi',     'SERVICE',  'CREATE', 'ACTIVE', 'SYSTEM', NOW(), '127.0.0.1'),
    (nextval('MAY.SEQ_PERMISSION'), 'SERVICE_UPDATE',   'Servis guncelleme yetkisi',    'SERVICE',  'UPDATE', 'ACTIVE', 'SYSTEM', NOW(), '127.0.0.1'),
    (nextval('MAY.SEQ_PERMISSION'), 'SERVICE_DELETE',   'Servis silme yetkisi',         'SERVICE',  'DELETE', 'ACTIVE', 'SYSTEM', NOW(), '127.0.0.1');

-- ROLE_PERMISSION: ADMIN - yeni yetkiler
INSERT INTO MAY.ROLE_PERMISSION (ID, ROLE_ID, PERMISSION_ID, CREATED_BY, CREATED_DATE, CREATED_IP)
SELECT
    nextval('MAY.SEQ_ROLE_PERMISSION'),
    (SELECT ID FROM MAY.ROLE WHERE NAME = 'ADMIN'),
    p.ID,
    'SYSTEM',
    NOW(),
    '127.0.0.1'
FROM MAY.PERMISSION p
WHERE p.MODULE = 'SERVICE';
